name: FransetWhitelist
version: '${project.version}'
main: me.kelsi.fransetwhitelist
api-version: 1.20
authors: [ Kelsi ]
description: plugin for vanila on Franset server
commands:
  wl:
    aliases: [wl, whitelist, fransetwhitelist, fransetwl]
    usage: "/wl add/remove <player>"